services:
  vanukov-site:
    build: ./vanukov-site 
    ports:
      - "80:80"
    volumes:
      - ./vanukov-site:/app
      - /app/node_modules 
    depends_on:
      - simulator
      - predict-server

  predict-server:
    build: ./predict-server
    ports:
      - "5002:5002"
    volumes:
      - ./predict-server:/app

  simulator:
    build: ./simulator
    ports:
      - "5001:5001"
    volumes:
      - ./simulator:/app
